@php
    /** @var array{generated_from: string, generated_by: string, generated_at: string} $footer */
    /** @var \App\Services\Dscsa\ComplianceReport\CompliancePageData $page */
@endphp
<div class="footer">
    <div>Generated from: {{ $footer['generated_from'] }}</div>
    <div>Generated by: {{ $footer['generated_by'] }}</div>
    <div>Generated at: {{ $footer['generated_at'] }}</div>
    <div class="page-num">Page {{ $page->pageNumber }} / {{ $page->totalPages }}</div>
</div>
