@php
    /** @var \App\Services\Dscsa\TransactionReport\LotPageData $page */
    /** @var \App\Services\Dscsa\TransactionReport\TransactionReportData $report */
    /** @var array{generated_from: string, generated_by: string, generated_at: string} $footer */
@endphp
@include('dscsa.compliance-report.partials.header', [
    'title' => 'Transaction Report ('.$page->referenceNumber.')',
    'subtitle' => 'ShipmentID: '.$page->shipmentId,
    'logoDataUri' => $report->logoDataUri ?? null,
    'compact' => false,
])

    <div class="section-title">Transaction Information</div>
    <table class="ti-table">
        <tr>
            <td class="ti-left">
                <table class="fields">
                    <tr><td class="label">Product Name</td><td class="value">{{ $page->productName }}</td></tr>
                    <tr><td class="label">NDC</td><td class="value mono">{{ $page->ndc }}</td></tr>
                    <tr><td class="label">Number Of Containers</td><td class="value">{{ number_format($page->numberOfContainers) }}</td></tr>
                    <tr><td class="label">Strength</td><td class="value">{{ $page->strength }}</td></tr>
                    <tr><td class="label">Dosage Form</td><td class="value">{{ $page->dosageForm }}</td></tr>
                    <tr><td class="label">Container Size</td><td class="value">{{ $page->containerSize }}</td></tr>
                    <tr><td class="label">Lot</td><td class="value mono">{{ $page->lot }}</td></tr>
                    <tr><td class="label">Expiration Date</td><td class="value">{{ $page->expirationDate }}</td></tr>
                    <tr><td class="label">Qty</td><td class="value">{{ number_format($page->qty) }}</td></tr>
                </table>
            </td>
            <td class="ti-right">
                <table class="fields">
                    <tr><td class="label">Manufacturer</td><td class="value">{{ $page->manufacturer }}</td></tr>
                    <tr><td class="label">Address</td><td class="value">{{ $page->manufacturerAddress }}</td></tr>
                    <tr><td class="label">City</td><td class="value">{{ $page->manufacturerCity }}</td></tr>
                    <tr><td class="label">State</td><td class="value">{{ $page->manufacturerState }}</td></tr>
                    <tr><td class="label">Zip</td><td class="value">{{ $page->manufacturerZip }}</td></tr>
                    <tr><td class="label">Processed Date</td><td class="value">{{ $page->processedDate }}</td></tr>
                    <tr><td class="label">Transaction Date</td><td class="value">{{ $page->transactionDate }}</td></tr>
                    <tr><td class="label">Reference #</td><td class="value mono">{{ $page->referenceNumber }}</td></tr>
                    <tr><td class="label">Tracking #</td><td class="value mono">{{ $page->trackingNumber }}</td></tr>
                    <tr><td class="label">Type</td><td class="value">{{ $page->type }}</td></tr>
                </table>
            </td>
        </tr>
    </table>

    <div class="section-title">Transaction History – Ownership Change</div>
    @if ($page->ownershipNote)
        <p class="note">{{ $page->ownershipNote }}</p>
    @endif
    <table class="history">
        <thead>
            <tr>
                <th>Sender</th>
                <th>Receiver</th>
                <th>Date</th>
                <th class="order">Order</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($page->ownershipRows as $row)
                <tr>
                    <td>{!! nl2br(e($row['sender'])) !!}</td>
                    <td>{!! nl2br(e($row['receiver'])) !!}</td>
                    <td>{{ $row['date'] }}</td>
                    <td class="order">{{ $row['order'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" class="empty">—</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    @include('dscsa.compliance-report.partials.legal-statements', [
        'legalStatement' => $page->legalStatement,
        'directPurchaseStatement' => $page->directPurchaseStatement,
        'receivedPrevWholesalerStatement' => $page->receivedPrevWholesalerStatement,
    ])

    <div class="footer">
        <div>Generated from: {{ $footer['generated_from'] }}</div>
        <div>Generated by: {{ $footer['generated_by'] }}</div>
        <div>Generated at: {{ $footer['generated_at'] }}</div>
    </div>
