<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Form FDA 3911 — Illegitimate Product Notification</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111; }
        h1 { font-size: 16px; margin-bottom: 4px; }
        h2 { font-size: 13px; margin-top: 18px; margin-bottom: 6px; border-bottom: 1px solid #ccc; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
        th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; vertical-align: top; }
        th { background: #f3f4f6; width: 32%; }
        .muted { color: #666; font-size: 10px; }
        .notice { background: #fffbeb; border: 1px solid #f59e0b; padding: 8px; margin-bottom: 12px; }
    </style>
</head>
<body>
    <h1>Form FDA 3911 — Illegitimate Product Notification (Draft)</h1>
    <p class="muted">Generated by TracePharma on {{ now()->toDateTimeString() }}. Submit via FDA CDER NextGen 3911 platform or email to drugnotifications@fda.hhs.gov.</p>

    <div class="notice">
        DSCSA requires notification within 24 hours of determining a product is illegitimate.
        @if($report->due_at)
            Reporting due by: {{ $report->due_at->toDateTimeString() }}.
        @endif
    </div>

    <h2>Submission details</h2>
    <table>
        <tr><th>Classification</th><td>{{ $report->classification?->label() ?? '—' }}</td></tr>
        <tr><th>Date illegitimate product determined</th><td>{{ $report->determined_at?->toDateString() ?? '—' }}</td></tr>
        <tr><th>Report status</th><td>{{ $report->status?->label() ?? '—' }}</td></tr>
        @if($report->incident_number)
        <tr><th>FDA incident number</th><td>{{ $report->incident_number }}</td></tr>
        @endif
    </table>

    <h2>Notifier</h2>
    <table>
        <tr><th>Name</th><td>{{ $report->notifier_name ?? '—' }}</td></tr>
        <tr><th>Title</th><td>{{ $report->notifier_title ?? '—' }}</td></tr>
        <tr><th>Phone</th><td>{{ $report->notifier_phone ?? '—' }}</td></tr>
        <tr><th>Email</th><td>{{ $report->notifier_email ?? '—' }}</td></tr>
    </table>

    <h2>Facility</h2>
    <table>
        <tr><th>Facility name</th><td>{{ $report->facility_name ?? '—' }}</td></tr>
        <tr><th>GLN</th><td>{{ $report->facility_gln ?? '—' }}</td></tr>
        <tr><th>Address</th><td>{{ $report->facility_address ?? '—' }}</td></tr>
    </table>

    <h2>Product</h2>
    <table>
        <tr><th>NDC</th><td>{{ $report->product_ndc ?? '—' }}</td></tr>
        <tr><th>Product name</th><td>{{ $report->product_name ?? '—' }}</td></tr>
        <tr><th>GTIN</th><td>{{ $report->product_gtin ?? '—' }}</td></tr>
        <tr><th>Lot</th><td>{{ $report->lot ?? '—' }}</td></tr>
        <tr><th>Serial</th><td>{{ $report->serial ?? '—' }}</td></tr>
        <tr><th>Strength</th><td>{{ $report->strength ?? '—' }}</td></tr>
        <tr><th>Dosage form</th><td>{{ $report->dosage_form ?? '—' }}</td></tr>
    </table>

    <h2>Circumstances</h2>
    <p>{{ $report->circumstances ?? '—' }}</p>

    @if($report->tradingPartner)
    <h2>Trading partner</h2>
    <table>
        <tr><th>Name</th><td>{{ $report->tradingPartner->name }}</td></tr>
        <tr><th>GLN</th><td>{{ $report->tradingPartner->gln }}</td></tr>
    </table>
    @endif
</body>
</html>
