<?php

namespace App\Filament\App\Resources\SsccLabels\Schemas;

use App\Enums\SsccAllocationMode;
use App\Models\SsccLabel;
use App\Support\Tracing\AssetTrackingUrl;
use App\Support\Ui\CopyableIdentifier;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Enums\FontFamily;

class SsccLabelInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('SSCC')
                    ->compact()
                    ->schema([
                        CopyableIdentifier::applyToEntry(
                            TextEntry::make('hrt')
                                ->label('Human readable')
                                ->fontFamily(FontFamily::Mono),
                        ),
                        CopyableIdentifier::applyToEntry(
                            TextEntry::make('sscc_18')
                                ->label('SSCC-18')
                                ->fontFamily(FontFamily::Mono)
                                ->url(fn (SsccLabel $record): ?string => AssetTrackingUrl::url(
                                    AssetTrackingUrl::scanForSsccLabel([
                                        'sscc18' => $record->sscc_18,
                                        'element_string' => $record->element_string,
                                    ]),
                                )),
                        ),
                        CopyableIdentifier::applyToEntry(
                            TextEntry::make('sscc_urn')
                                ->label('EPC URI')
                                ->fontFamily(FontFamily::Mono)
                                ->url(fn (SsccLabel $record): ?string => filled($record->sscc_urn)
                                    ? AssetTrackingUrl::url((string) $record->sscc_urn)
                                    : null),
                        ),
                        CopyableIdentifier::applyToEntry(
                            TextEntry::make('element_string')
                                ->label('Barcode element string')
                                ->fontFamily(FontFamily::Mono)
                                ->url(fn (SsccLabel $record): ?string => filled($record->element_string)
                                    ? AssetTrackingUrl::url((string) $record->element_string)
                                    : null),
                        ),
                    ]),
                Section::make('Allocation')
                    ->compact()
                    ->schema([
                        TextEntry::make('allocation_mode')
                            ->badge()
                            ->formatStateUsing(fn (?SsccAllocationMode $state): string => $state?->label() ?? '—'),
                        TextEntry::make('company_prefix'),
                        TextEntry::make('extension_digit'),
                        TextEntry::make('serial_reference')
                            ->copyable(),
                        TextEntry::make('batch.label_count')
                            ->label('Batch size')
                            ->placeholder('—'),
                        TextEntry::make('creator.name')
                            ->label('Generated by')
                            ->placeholder('—'),
                        TextEntry::make('created_at')
                            ->dateTime(),
                    ])
                    ->columns(2),
                Section::make('Shipment')
                    ->compact()
                    ->schema([
                        TextEntry::make('ship_to_name')
                            ->placeholder('—'),
                        TextEntry::make('ship_to_gln')
                            ->copyable()
                            ->placeholder('—'),
                        TextEntry::make('notes')
                            ->placeholder('—')
                            ->columnSpanFull(),
                    ])
                    ->columns(2),
            ]);
    }
}
